name = input("Name : ")
branch = input("Branch : ")
gender = input("Gender : ")
college = input("College : ")
age  = int(input("Age : "))
print("\nName:",name)
print("\nBranch:",branch)
print("\nGender:",gender)
print("\nCollege:",college)
print("\nAge:",age)
